/**
 * 
 */
package com.pathfinder.util.properties;

/**
 * @author tim
 * 
 */
public enum PropertiesKey {
	EXAMPLE_STRING, EXAMPLE_NOT_FOUND, EXAMPLE_INT, EXAMPLE_INT_NOT_FOUND, DATA_LOAD_INTERVALL, RAPLA_BASE_URL, IMAGE_BASE_URL, DATA_LOAD_INTERVAL_FREE_ROOMS, TABLE_CACHE_RATE, BACK_TO_HOME_TIMER, DEFAULT_IMAGE_NAME;
}
